-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 20:47:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jarvis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jarvis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jarvis` DEFAULT CHARACTER SET utf8 ;
USE `jarvis` ;

-- -----------------------------------------------------
-- Table `jarvis`.`Domicile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Domicile` (
  `id_domicile` INT NOT NULL AUTO_INCREMENT,
  `annee_construction` DATE NULL,
  `superficie` DOUBLE NULL,
  PRIMARY KEY (`id_domicile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Proprietaire` (
  `id_pro` INT NOT NULL AUTO_INCREMENT,
  `Domicile_id_domicile` INT NOT NULL,
  PRIMARY KEY (`id_pro`, `Domicile_id_domicile`),
  INDEX `fk_Proprietaire_Domicile1_idx` (`Domicile_id_domicile` ASC) VISIBLE,
  CONSTRAINT `fk_Proprietaire_Domicile1`
    FOREIGN KEY (`Domicile_id_domicile`)
    REFERENCES `jarvis`.`Domicile` (`id_domicile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Membre` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `lien_parente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_m`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Co-proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Co-proprietaire` (
  `id_co-pro` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_co-pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`x`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`x` (
  `id_x` INT NOT NULL AUTO_INCREMENT,
  `Proprietaire_id_pro` INT NOT NULL,
  `Membre_id_m` INT NOT NULL,
  `Co-proprietaire_id_co-pro` INT NOT NULL,
  PRIMARY KEY (`id_x`, `Proprietaire_id_pro`, `Membre_id_m`, `Co-proprietaire_id_co-pro`),
  INDEX `fk_x_Proprietaire1_idx` (`Proprietaire_id_pro` ASC) VISIBLE,
  INDEX `fk_x_Membre1_idx` (`Membre_id_m` ASC) VISIBLE,
  INDEX `fk_x_Co-proprietaire1_idx` (`Co-proprietaire_id_co-pro` ASC) VISIBLE,
  CONSTRAINT `fk_x_Proprietaire1`
    FOREIGN KEY (`Proprietaire_id_pro`)
    REFERENCES `jarvis`.`Proprietaire` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_Membre1`
    FOREIGN KEY (`Membre_id_m`)
    REFERENCES `jarvis`.`Membre` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_Co-proprietaire1`
    FOREIGN KEY (`Co-proprietaire_id_co-pro`)
    REFERENCES `jarvis`.`Co-proprietaire` (`id_co-pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Utilisateur` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `prenom_u` VARCHAR(100) NULL,
  `nom_u` VARCHAR(100) NULL,
  `date_de_naissance` DATE NULL,
  `email_u` VARCHAR(45) NULL,
  `sexe_u` VARCHAR(1) NULL,
  `mdp_u` VARCHAR(45) NULL,
  `x_id_x` INT NOT NULL,
  `x_Proprietaire_id_pro` INT NOT NULL,
  `x_Membre_id_m` INT NOT NULL,
  `x_Co-proprietaire_id_co-pro` INT NOT NULL,
  PRIMARY KEY (`id_u`, `x_id_x`, `x_Proprietaire_id_pro`, `x_Membre_id_m`, `x_Co-proprietaire_id_co-pro`),
  INDEX `fk_Utilisateur_x1_idx` (`x_id_x` ASC, `x_Proprietaire_id_pro` ASC, `x_Membre_id_m` ASC, `x_Co-proprietaire_id_co-pro` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_x1`
    FOREIGN KEY (`x_id_x` , `x_Proprietaire_id_pro` , `x_Membre_id_m` , `x_Co-proprietaire_id_co-pro`)
    REFERENCES `jarvis`.`x` (`id_x` , `Proprietaire_id_pro` , `Membre_id_m` , `Co-proprietaire_id_co-pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Appareils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Appareils` (
  `id_appareil` INT NOT NULL AUTO_INCREMENT,
  `nom_appareil` VARCHAR(45) NULL,
  `type_appareil` VARCHAR(45) NULL,
  PRIMARY KEY (`id_appareil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Piece` (
  `id_piece` INT NOT NULL AUTO_INCREMENT,
  `nom_piece` VARCHAR(45) NULL,
  `Domicile_id_domicile` INT NOT NULL,
  `Appareils_id_appareil` INT NOT NULL,
  PRIMARY KEY (`id_piece`, `Domicile_id_domicile`, `Appareils_id_appareil`),
  INDEX `fk_Piece_Domicile1_idx` (`Domicile_id_domicile` ASC) VISIBLE,
  INDEX `fk_Piece_Appareils1_idx` (`Appareils_id_appareil` ASC) VISIBLE,
  CONSTRAINT `fk_Piece_Domicile1`
    FOREIGN KEY (`Domicile_id_domicile`)
    REFERENCES `jarvis`.`Domicile` (`id_domicile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piece_Appareils1`
    FOREIGN KEY (`Appareils_id_appareil`)
    REFERENCES `jarvis`.`Appareils` (`id_appareil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Inviter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Inviter` (
  `Utilisateur_id_u` INT NOT NULL,
  `Proprietaire_id_pro` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_id_u`, `Proprietaire_id_pro`),
  INDEX `fk_Utilisateur_has_Proprietaire_Proprietaire1_idx` (`Proprietaire_id_pro` ASC) VISIBLE,
  INDEX `fk_Utilisateur_has_Proprietaire_Utilisateur_idx` (`Utilisateur_id_u` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_has_Proprietaire_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_u`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Proprietaire_Proprietaire1`
    FOREIGN KEY (`Proprietaire_id_pro`)
    REFERENCES `jarvis`.`Proprietaire` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Contenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Contenir` (
  `Domicile_id_domicile` INT NOT NULL,
  `Utilisateur_id_u` INT NOT NULL,
  `Utilisateur_x_id_x` INT NOT NULL,
  `Utilisateur_x_Proprietaire_id_pro` INT NOT NULL,
  `Utilisateur_x_Membre_id_m` INT NOT NULL,
  `Utilisateur_x_Co-proprietaire_id_co-pro` INT NOT NULL,
  PRIMARY KEY (`Domicile_id_domicile`, `Utilisateur_id_u`, `Utilisateur_x_id_x`, `Utilisateur_x_Proprietaire_id_pro`, `Utilisateur_x_Membre_id_m`, `Utilisateur_x_Co-proprietaire_id_co-pro`),
  INDEX `fk_Domicile_has_Utilisateur_Utilisateur1_idx` (`Utilisateur_id_u` ASC, `Utilisateur_x_id_x` ASC, `Utilisateur_x_Proprietaire_id_pro` ASC, `Utilisateur_x_Membre_id_m` ASC, `Utilisateur_x_Co-proprietaire_id_co-pro` ASC) VISIBLE,
  INDEX `fk_Domicile_has_Utilisateur_Domicile1_idx` (`Domicile_id_domicile` ASC) VISIBLE,
  CONSTRAINT `fk_Domicile_has_Utilisateur_Domicile1`
    FOREIGN KEY (`Domicile_id_domicile`)
    REFERENCES `jarvis`.`Domicile` (`id_domicile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domicile_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_u` , `Utilisateur_x_id_x` , `Utilisateur_x_Proprietaire_id_pro` , `Utilisateur_x_Membre_id_m` , `Utilisateur_x_Co-proprietaire_id_co-pro`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u` , `x_id_x` , `x_Proprietaire_id_pro` , `x_Membre_id_m` , `x_Co-proprietaire_id_co-pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
